// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applications": {
            "get": {
                "description": "ユーザーの全ての応募履歴を案件情報と共に取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "応募"
                ],
                "summary": "応募一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "応募一覧の取得成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Application"
                            }
                        }
                    },
                    "400": {
                        "description": "無効なパラメータ",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/applications/{application_id}/matching": {
            "post": {
                "description": "応募を承認してマッチングを作成します。応募のステータスを「accepted」に、案件のステータスを「matched」に更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "マッチング"
                ],
                "summary": "マッチング作成",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "応募ID",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "マッチング作成情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_matching.CreateMatchingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Matching"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "403": {
                        "description": "この操作を行う権限がありません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "404": {
                        "description": "案件が見つかりません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/applications/{application_id}/status": {
            "put": {
                "description": "応募のステータスを更新します（案件作成者のみ可能）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "応募"
                ],
                "summary": "応募ステータス更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "応募ID",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新するステータス情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_application.UpdateApplicationStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Application"
                        }
                    },
                    "400": {
                        "description": "無効なパラメータ",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "403": {
                        "description": "この応募のステータスを更新する権限がありません\",",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "404": {
                        "description": "応募が見つかりません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "メールアドレスとパスワードで認証し、トークンを発行します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "認証"
                ],
                "summary": "ログイン",
                "parameters": [
                    {
                        "description": "ログイン情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ログイン成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "400": {
                        "description": "無効なパラメータ",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "メールアドレスまたはパスワードが間違っています",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "新規ユーザーを登録し、認証トークンを発行します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "認証"
                ],
                "summary": "ユーザー登録",
                "parameters": [
                    {
                        "description": "登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_auth.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "登録成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "400": {
                        "description": "無効なパラメータ",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "409": {
                        "description": "メールアドレスが既に使用されています",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/cases": {
            "get": {
                "description": "全ての案件情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "案件"
                ],
                "summary": "案件一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "案件一覧",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "array",
                                                "items": {
                                                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Case"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/cases/{id}": {
            "get": {
                "description": "指定されたIDの案件情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "案件"
                ],
                "summary": "案件詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "案件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "案件情報",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Case"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "404": {
                        "description": "案件が見つかりません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "指定された案件の情報を更新します（案件作成者のみ可能）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "案件"
                ],
                "summary": "案件更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "案件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新する案件情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_case.CreateCaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Case"
                        }
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "403": {
                        "description": "この操作を行う権限がありません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "404": {
                        "description": "案件が見つかりません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/matchings/{id}/confirm-arrival": {
            "post": {
                "description": "マッチング成立後の到着確認を行います。依頼者とヘルパー両方の確認が完了すると、マッチングが完了状態になります。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "マッチング"
                ],
                "summary": "到着確認",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "マッチングID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Matching"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "リクエストが不正です / この案件は募集を終了しています / 確認期限が過ぎています",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "403": {
                        "description": "この操作を行う権限がありません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/reviews": {
            "get": {
                "description": "ユーザーのレビュー一覧を取得します。user_idクエリパラメータを指定すると、特定のユーザーに対するレビューのみを取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "レビュー"
                ],
                "summary": "レビュー一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID（指定しない場合は全レビューを取得）",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "レビュー一覧",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Review"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "マッチング完了後、相手ユーザーへのレビューを作成します。1つのマッチングにつき1人のユーザーは1回のみレビュー可能です。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "レビュー"
                ],
                "summary": "レビュー作成",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "レビュー情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_review.CreateReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "レビュー作成成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Review"
                        }
                    },
                    "400": {
                        "description": "リクエストが不正です / 完了していないマッチングにはレビューできません / このマッチングに関係のないユーザーにレビューはできません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "403": {
                        "description": "このマッチングにレビューを投稿する権限がありません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "404": {
                        "description": "マッチングが見つかりません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "409": {
                        "description": "既にレビューを投稿済みです",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー / 信頼スコアの更新に失敗しました",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "put": {
                "description": "ログインユーザーの表示名を更新します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー"
                ],
                "summary": "ユーザー情報更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新するユーザー情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_user.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新後のユーザー情報",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "404": {
                        "description": "ユーザーが見つかりません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "ユーザーと関連する全てのデータ（レビュー、マッチング、応募、案件）を削除します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー"
                ],
                "summary": "ユーザー削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token} 形式",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "ユーザーIDに基づいてユーザーの基本情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー"
                ],
                "summary": "ユーザー情報取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ユーザー情報",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "無効なユーザーID",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "404": {
                        "description": "ユーザーが見つかりません",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}/reviews": {
            "get": {
                "description": "指定されたユーザーが受け取ったレビューの一覧を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー"
                ],
                "summary": "ユーザーのレビュー一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "レビュー一覧",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Review"
                            }
                        }
                    },
                    "400": {
                        "description": "無効なユーザーID",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_kageyama0_chotto-rental_pkg_util.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_kageyama0_chotto-rental_internal_model.Application": {
            "description": "応募情報",
            "type": "object",
            "properties": {
                "applicant": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.User"
                },
                "applicantID": {
                    "type": "string"
                },
                "case": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Case"
                },
                "caseID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_kageyama0_chotto-rental_internal_model.Case": {
            "description": "案件情報",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "durationMinutes": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "reward": {
                    "type": "integer"
                },
                "scheduledDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.User"
                },
                "userID": {
                    "description": "案件の依頼者",
                    "type": "string"
                }
            }
        },
        "github_com_kageyama0_chotto-rental_internal_model.Matching": {
            "description": "マッチング情報",
            "type": "object",
            "properties": {
                "arrivalConfirmationDeadline": {
                    "type": "string"
                },
                "arrivalConfirmedByHelper": {
                    "type": "boolean"
                },
                "arrivalConfirmedByRequester": {
                    "type": "boolean"
                },
                "case": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Case"
                },
                "caseID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "helper": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.User"
                },
                "helperID": {
                    "description": "案件を受けたユーザー",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "meetingLocation": {
                    "type": "string"
                },
                "requester": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.User"
                },
                "requesterID": {
                    "description": "案件の依頼者",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_kageyama0_chotto-rental_internal_model.Review": {
            "description": "レビュー情報",
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "string"
                },
                "matching": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.Matching"
                },
                "matchingID": {
                    "type": "string"
                },
                "reviewedUser": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.User"
                },
                "reviewedUserID": {
                    "description": "レビューを書かれたユーザー",
                    "type": "string"
                },
                "reviewer": {
                    "$ref": "#/definitions/github_com_kageyama0_chotto-rental_internal_model.User"
                },
                "reviewerID": {
                    "description": "レビューを書いたユーザー",
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_kageyama0_chotto-rental_internal_model.User": {
            "description": "ユーザー情報",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "noShowCount": {
                    "type": "integer"
                },
                "passwordHash": {
                    "type": "string"
                },
                "trustScore": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_kageyama0_chotto-rental_pkg_util.Response": {
            "description": "HTTPレスポンス",
            "type": "object",
            "properties": {
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_handler_application.CreateApplicationRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_handler_application.UpdateApplicationStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "accepted",
                        "rejected"
                    ]
                }
            }
        },
        "internal_handler_auth.LoginRequest": {
            "description": "ログインリクエスト",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_handler_auth.SignupRequest": {
            "description": "ユーザー登録リクエスト",
            "type": "object",
            "required": [
                "displayName",
                "email",
                "password"
            ],
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "internal_handler_case.CreateCaseRequest": {
            "type": "object",
            "required": [
                "description",
                "durationMinutes",
                "location",
                "reward",
                "scheduledDate",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "durationMinutes": {
                    "type": "integer",
                    "minimum": 1
                },
                "location": {
                    "type": "string"
                },
                "reward": {
                    "type": "integer",
                    "minimum": 0
                },
                "scheduledDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_handler_matching.CreateMatchingRequest": {
            "type": "object",
            "required": [
                "meetingLocation"
            ],
            "properties": {
                "meetingLocation": {
                    "type": "string"
                }
            }
        },
        "internal_handler_review.CreateReviewRequest": {
            "type": "object",
            "required": [
                "reviewedUserId",
                "score"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "reviewedUserId": {
                    "type": "string"
                },
                "score": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                }
            }
        },
        "internal_handler_user.UpdateUserRequest": {
            "type": "object",
            "required": [
                "displayName"
            ],
            "properties": {
                "displayName": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "「Bearer 」の後にJWTトークンを付与してください",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Chotto Rental API",
	Description:      "ちょっとレンタルサービスのAPI仕様書",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
